INSERT INTO items (id, name, type_id, unit_id, created_at, update_at)
VALUES ('x7p2md', 'Vann', 1, 3, NOW(), NOW()),
       ('q3lmvn', 'Knekkebrød', 1, 2, NOW(), NOW()),
       ('f9ztbc', 'Havregryn', 1, 2, NOW(), NOW()),
       ('j5cblq', 'Hermetiske bønner', 1, 1, NOW(), NOW()),
       ('u2ywrn', 'Hermetisk kjøtt', 1, 1, NOW(), NOW()),
       ('a4vnxz', 'Hermetiske grønnsaker', 1, 1, NOW(), NOW()),
       ('e7z0kc', 'Hermetisk frukt', 1, 1, NOW(), NOW()),
       ('r6t1qe', 'Suppeposer', 1, 1, NOW(), NOW()),
       ('h1k3wd', 'Tørrmelk', 1, 2, NOW(), NOW()),
       ('s0qjya', 'Kjekspakke', 1, 1, NOW(), NOW()),
       ('m8bylc', 'Nøtter og tørrfrukt', 1, 2, NOW(), NOW()),
       ('d5rnmu', 'Energibarer', 1, 1, NOW(), NOW()),
       ('n3vtxz', 'Pulverkaffe', 1, 2, NOW(), NOW()),
       ('v6b2qp', 'Sukker', 1, 2, NOW(), NOW()),
       ('l0smrd', 'Salt', 1, 2, NOW(), NOW()),
       ('c9apfy', 'Matolje', 1, 3, NOW(), NOW()),
       ('z8qjlu', 'Ris', 1, 2, NOW(), NOW()),
       ('b4tmxw', 'Pasta', 1, 2, NOW(), NOW()),
       ('k2yced', 'Te-pose', 1, 1, NOW(), NOW()),
       ('y7wcrd', 'Hermetisk fisk', 1, 2, NOW(), NOW()),
       ('t1fxop', 'Feltmat', 1, 1, NOW(), NOW()),
       ('u7ibxw', 'Stearinlys', 2, 1, NOW(), NOW()),
       ('4qmhmf', 'Fyrstikker', 2, 1, NOW(), NOW()),
       ('zdtfiq', 'Lommelykt', 2, 1, NOW(), NOW()),
       ('2gbbvn', 'Batterier', 2, 1, NOW(), NOW()),
       ('uua2p3', 'Ved', 2, 3, NOW(), NOW()),
       ('5re6xq', 'Stormkjøkken m/brensel', 2, 1, NOW(), NOW()),
       ('6fkrzf', 'Pledd', 2, 1, NOW(), NOW()),
       ('yeq3c1', 'Ullundertøy', 2, 1, NOW(), NOW()),
       ('sg1m46', 'DAB-radio', 3, 1, NOW(), NOW()),
       ('4cgqul', 'Powerbank', 3, 1, NOW(), NOW()),
       ('q7be58', 'Ladekabler', 3, 1, NOW(), NOW()),
       ('rapaqh', 'Oversikt nødnummer', 3, 1, NOW(), NOW()),
       ('0la0fz', 'Kart over nærområdet', 3, 1, NOW(), NOW()),
       ('ijho3a', 'Toalettpapir', 4, 1, NOW(), NOW()),
       ('saenyt', 'Våtservietter', 4, 1, NOW(), NOW()),
       ('iy3lt1', 'Antiback', 4, 3, NOW(), NOW()),
       ('g9zbfx', 'Såpe', 4, 3, NOW(), NOW()),
       ('5f0jja', 'Tannbørste', 4, 1, NOW(), NOW()),
       ('3h4dox', 'Tannkrem', 4, 1, NOW(), NOW()),
       ('g6w798', 'Personlige medisiner', 4, 1, NOW(), NOW()),
       ('i9qrrj', 'Smertestillende', 4, 1, NOW(), NOW()),
       ('3bkly8', 'Førstehjelsskrin', 4, 1, NOW(), NOW()),
       ('slq7ef', 'Plaster', 4, 1, NOW(), NOW()),
       ('99abjl', 'Termometer', 4, 1, NOW(), NOW()),
       ('3ya18o', 'Bandasje', 4, 1, NOW(), NOW()),
       ('r31sbf', 'Tørkepapir', 4, 1, NOW(), NOW()),
       ('lwa4ei', 'Innsektsspray', 4, 1, NOW(), NOW()),
       ('af3qs7', 'Kontanter', 5, 1, NOW(), NOW()),
       ('hvv2bp', 'Multiverktøy', 5, 1, NOW(), NOW()),
       ('alb66x', 'Søppelsekker', 5, 1, NOW(), NOW()),
       ('uigaap', 'Tape', 5, 1, NOW(), NOW()),
       ('8apw2d', 'Arbeidshansker', 5, 1, NOW(), NOW()),
       ('njl5oa', 'Notatblokk m/penn', 5, 1, NOW(), NOW()),
       ('jaw98g', 'Lommekniv', 5, 1, NOW(), NOW()),
       ('00d1ex', 'Bøtte m/lokk', 5, 1, NOW(), NOW()),
       ('rzj91b', 'Presenning', 5, 1, NOW(), NOW());
